apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysqlservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.25Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysqlservice
  labels:
    app: mysqlservice
spec:
  selector:
    matchLabels:
      app: mysqlservice
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqlservice
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: PASSWORD
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    create database if not exists userservicedb;
    use userservicedb;
    CREATE USER IF NOT EXISTS 'userservice'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
    GRANT ALL PRIVILEGES ON userservicedb.* TO 'userservice'@'%';
    FLUSH PRIVILEGES;
    create database if not exists tradeservicedb;
    use tradeservicedb;
    CREATE USER IF NOT EXISTS 'tradeservice'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
    GRANT ALL PRIVILEGES ON tradeservicedb.* TO 'tradeservice'@'%';
    FLUSH PRIVILEGES;
    create database if not exists portfolioservicedb;
    use portfolioservicedb;
    CREATE USER IF NOT EXISTS 'portfolioservice'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
    GRANT ALL PRIVILEGES ON portfolioservicedb.* TO 'portfolioservice'@'%';
    FLUSH PRIVILEGES;
