version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME:"root"
      - MONGO_INITDB_ROOT_PASSWORD:"password"
      - MONGO_INITDB_DATABASE:"stockservicedb"
      - MONGO_DB_USERNAME:"admin"
      - MONGO_DB_PASSWORD:"password"
    volumes:
      - ./mongo/data/:/data/db/
      - ./mongo/log/:/var/log/mongodb/      

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME:"root"
      - ME_CONFIG_MONGODB_ADMINPASSWORD:"password"
    depends_on:
      - mongo
  config-service:
    container_name: config-service
    build: ./config-service
    ports:
      - "8888:8888"
    depends_on:
      - mongo
  discovery-service:
    container_name: discovery-service
    build: ./discovery-service
    ports:
      - "8761:8761"
    depends_on:
      - mongo
      - config-service
  user-service: 
    container_name: user-service
    build: ./user-service
    ports: 
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=uat
      - EUREKA_SERVICE_URL=http://discovery-service:8761/eureka
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=stockservicedb
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_URI=mongodb://mongo/stockservicedb
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=password
      - SPRING_DATA_MONGODB_DATABASE=stockservicedb
    depends_on:
      - mongo
      - config-service
      - discovery-service
  stock-service-ui: 
    container_name: stock-service-ui
    build: ../stock-service-ui
    ports: 
      - "8080:3000"
    depends_on:
      - mongo
      - config-service
      - discovery-service
      - user-service
  


