package com.sachin.tradeservice.sm.constants;

public enum TradeStatusEnum {

	NEW_ORDER, STOCK_RETRIEVE_PENDING, STOCK_RETRIEVED, STOCK_RETRIEVE_FAIL, STOCK_ORDER_PENDING, STOCK_ORDERED, STOCK_ORDER_FAIL, PORTFOLIO_UPDATE_PENDING, PORTFOLIO_UPDATED, PORTFOLIO_UPDATE_FAIL
}

