package com.sachin.tradeservice.sm.constants;

public enum TradeEventsEnum {
 RETRIEVE_STOCK, RETRIEVE_STOCK_SUCCESS, RETRIEVE_STOCK_FAIL, ORDER_STOCK, ORDER_STOCK_SUCCESS, ORDER_STOCK_FAIL, UPDATE_PORTFOLIO, UPDATE_PORTFOLIO_SUCCESS, UPDATE_PORTFOLIO_FAIL
}
