openapi: "3.0.0"
info:
  title: "Stock Finance Event Generator"
  description: "Generates stock related data events"
  version: 1.0.0
servers:
  - url: "http://localhost:8083/stockdetailsservice/v1"
components:
  schemas:
    stockRequest:
      title: "Structure of request for generating stock event"
      type: object
      properties:
        id:
          type: string
          title: "id for the request"
        name:
          type: string
          maxLength: 25
          title: "name of the stock"
        datetime:
          type: string
          title: "datetime for the quote"
          pattern: "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]$"
          example: "2021-01-30 05:30"
      required:
        [id, name]
    stockEvent:
      type: object
      properties:
        id:
          type: string
          title: "event id"
        name:
          type: string
          title: "name of the stock"
        datetime:
          type: string
          title: "datetime for the event"
          pattern: "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]$"
          example: "2021-01-30 08:30"
    errorDetails:
      type: object
      properties:
        errorcode:
          type: string
        errordesc:
          type: string
paths:
  /stockQuote:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/stockRequest'
      responses:
        200:
          description: "event response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stockEvent'
        400:
          description: "error response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorDetails'
    